// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 登陆方式
type LoginType int32

const (
	LoginType_ACCOUNT LoginType = 0
	LoginType_PHONE   LoginType = 1
	LoginType_WECHAT  LoginType = 2
	LoginType_QQ      LoginType = 3
)

var LoginType_name = map[int32]string{
	0: "ACCOUNT",
	1: "PHONE",
	2: "WECHAT",
	3: "QQ",
}
var LoginType_value = map[string]int32{
	"ACCOUNT": 0,
	"PHONE":   1,
	"WECHAT":  2,
	"QQ":      3,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_a05133934c716004, []int{0}
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	SchoolId             int32    `protobuf:"varint,4,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	ClassId              int32    `protobuf:"varint,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	AreaId               int32    `protobuf:"varint,6,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	IdentityStatus       int32    `protobuf:"varint,7,opt,name=identity_status,json=identityStatus,proto3" json:"identity_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_a05133934c716004, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *User) GetSchoolId() int32 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

func (m *User) GetClassId() int32 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *User) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *User) GetIdentityStatus() int32 {
	if m != nil {
		return m.IdentityStatus
	}
	return 0
}

type RegData struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegData) Reset()         { *m = RegData{} }
func (m *RegData) String() string { return proto.CompactTextString(m) }
func (*RegData) ProtoMessage()    {}
func (*RegData) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_a05133934c716004, []int{1}
}
func (m *RegData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegData.Unmarshal(m, b)
}
func (m *RegData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegData.Marshal(b, m, deterministic)
}
func (dst *RegData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegData.Merge(dst, src)
}
func (m *RegData) XXX_Size() int {
	return xxx_messageInfo_RegData.Size(m)
}
func (m *RegData) XXX_DiscardUnknown() {
	xxx_messageInfo_RegData.DiscardUnknown(m)
}

var xxx_messageInfo_RegData proto.InternalMessageInfo

func (m *RegData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// 登陆所需结构
type PLoginData struct {
	Phone                string    `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	VerifyCode           string    `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	Account              string    `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Password             string    `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	LoginType            LoginType `protobuf:"varint,5,opt,name=login_type,json=loginType,proto3,enum=proto.LoginType" json:"login_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PLoginData) Reset()         { *m = PLoginData{} }
func (m *PLoginData) String() string { return proto.CompactTextString(m) }
func (*PLoginData) ProtoMessage()    {}
func (*PLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_a05133934c716004, []int{2}
}
func (m *PLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLoginData.Unmarshal(m, b)
}
func (m *PLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLoginData.Marshal(b, m, deterministic)
}
func (dst *PLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLoginData.Merge(dst, src)
}
func (m *PLoginData) XXX_Size() int {
	return xxx_messageInfo_PLoginData.Size(m)
}
func (m *PLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_PLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_PLoginData proto.InternalMessageInfo

func (m *PLoginData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PLoginData) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *PLoginData) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PLoginData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PLoginData) GetLoginType() LoginType {
	if m != nil {
		return m.LoginType
	}
	return LoginType_ACCOUNT
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*RegData)(nil), "proto.regData")
	proto.RegisterType((*PLoginData)(nil), "proto.PLoginData")
	proto.RegisterEnum("proto.LoginType", LoginType_name, LoginType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountClient interface {
	// 登陆(账号或手机号)
	Login(ctx context.Context, in *PLoginData, opts ...client.CallOption) (*User, error)
	Reg(ctx context.Context, in *PSingleString, opts ...client.CallOption) (*User, error)
	GetVerifyCode(ctx context.Context, in *PSingleString, opts ...client.CallOption) (*PBool, error)
	GetUserInfo(ctx context.Context, in *PInt32, opts ...client.CallOption) (*User, error)
}

type accountClient struct {
	c           client.Client
	serviceName string
}

func NewAccountClient(serviceName string, c client.Client) AccountClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto"
	}
	return &accountClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountClient) Login(ctx context.Context, in *PLoginData, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Login", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Reg(ctx context.Context, in *PSingleString, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Reg", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetVerifyCode(ctx context.Context, in *PSingleString, opts ...client.CallOption) (*PBool, error) {
	req := c.c.NewRequest(c.serviceName, "Account.GetVerifyCode", in)
	out := new(PBool)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserInfo(ctx context.Context, in *PInt32, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "Account.GetUserInfo", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	// 登陆(账号或手机号)
	Login(context.Context, *PLoginData, *User) error
	Reg(context.Context, *PSingleString, *User) error
	GetVerifyCode(context.Context, *PSingleString, *PBool) error
	GetUserInfo(context.Context, *PInt32, *User) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Account{hdlr}, opts...))
}

type Account struct {
	AccountHandler
}

func (h *Account) Login(ctx context.Context, in *PLoginData, out *User) error {
	return h.AccountHandler.Login(ctx, in, out)
}

func (h *Account) Reg(ctx context.Context, in *PSingleString, out *User) error {
	return h.AccountHandler.Reg(ctx, in, out)
}

func (h *Account) GetVerifyCode(ctx context.Context, in *PSingleString, out *PBool) error {
	return h.AccountHandler.GetVerifyCode(ctx, in, out)
}

func (h *Account) GetUserInfo(ctx context.Context, in *PInt32, out *User) error {
	return h.AccountHandler.GetUserInfo(ctx, in, out)
}

func init() { proto.RegisterFile("proto/account.proto", fileDescriptor_account_a05133934c716004) }

var fileDescriptor_account_a05133934c716004 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0xd8, 0x8e, 0x27, 0x34, 0x98, 0xa1, 0x02, 0x13, 0x0e, 0x54, 0xbe, 0x50, 0x8a,
	0x54, 0x50, 0x22, 0x24, 0xae, 0x21, 0x54, 0xad, 0x25, 0xd4, 0x0f, 0x27, 0x85, 0x63, 0xb4, 0xf5,
	0x4e, 0xdd, 0x95, 0xcc, 0xae, 0xe5, 0xdd, 0x82, 0xf2, 0x9b, 0xf8, 0x0b, 0x1c, 0xf9, 0x61, 0xc8,
	0xeb, 0xb8, 0xa9, 0x2a, 0xc4, 0xc9, 0xf3, 0xde, 0x9b, 0x0f, 0xbf, 0x67, 0xc3, 0xd3, 0xb2, 0x52,
	0x46, 0xbd, 0x63, 0x59, 0xa6, 0x6e, 0xa5, 0x39, 0xb4, 0x08, 0x5d, 0xfb, 0x18, 0x87, 0x8d, 0x76,
	0xc5, 0x34, 0x35, 0x42, 0xfc, 0xdb, 0x81, 0xfe, 0xa5, 0xa6, 0x0a, 0x47, 0xd0, 0x15, 0x3c, 0x72,
	0xf6, 0x9c, 0x7d, 0x37, 0xed, 0x0a, 0x8e, 0x08, 0x7d, 0xc9, 0xbe, 0x53, 0xd4, 0xdd, 0x73, 0xf6,
	0x83, 0xd4, 0xd6, 0xf8, 0x0c, 0xbc, 0x9c, 0x24, 0xa7, 0x2a, 0xea, 0xd9, 0xbe, 0x0d, 0xc2, 0x97,
	0x10, 0xe8, 0xec, 0x46, 0xa9, 0x62, 0x25, 0x78, 0xd4, 0xb7, 0xd2, 0xa0, 0x21, 0x12, 0x8e, 0x2f,
	0x60, 0x90, 0x15, 0x4c, 0xeb, 0x5a, 0x73, 0xad, 0xe6, 0x5b, 0x9c, 0x70, 0x7c, 0x0e, 0x3e, 0xab,
	0x88, 0xd5, 0x8a, 0xd7, 0x2c, 0xac, 0x61, 0xc2, 0xf1, 0x35, 0x3c, 0x16, 0x9c, 0xa4, 0x11, 0x66,
	0xbd, 0xd2, 0x86, 0x99, 0x5b, 0x1d, 0xf9, 0xb6, 0x61, 0xd4, 0xd2, 0x0b, 0xcb, 0xc6, 0x53, 0xf0,
	0x2b, 0xca, 0x3f, 0x33, 0xc3, 0x70, 0x17, 0xdc, 0xf2, 0x46, 0x49, 0xb2, 0x1e, 0x82, 0xb4, 0x01,
	0xb5, 0x8d, 0x4c, 0xf1, 0x3b, 0x1b, 0x75, 0x1d, 0xff, 0x72, 0x00, 0xce, 0xbf, 0xa8, 0x5c, 0xc8,
	0xff, 0x0c, 0xbe, 0x82, 0xe1, 0x0f, 0xaa, 0xc4, 0xf5, 0x7a, 0x75, 0x6f, 0x1e, 0x1a, 0x6a, 0xae,
	0x38, 0x61, 0x04, 0xfe, 0x26, 0x63, 0x9b, 0x46, 0x90, 0xb6, 0x10, 0xc7, 0x30, 0x28, 0x99, 0xd6,
	0x3f, 0x55, 0xd5, 0xa4, 0x11, 0xa4, 0x77, 0x18, 0xdf, 0x03, 0x14, 0xf5, 0xe5, 0x95, 0x59, 0x97,
	0x64, 0xf3, 0x18, 0x4d, 0x9e, 0x34, 0xdf, 0xe2, 0x70, 0x2b, 0xa4, 0x81, 0xad, 0x97, 0xeb, 0x92,
	0x0e, 0x3e, 0xde, 0x9f, 0xc0, 0x21, 0xf8, 0xb3, 0xf9, 0xfc, 0xec, 0xf2, 0x74, 0x19, 0x76, 0x30,
	0x00, 0xf7, 0xfc, 0xe4, 0xec, 0xf4, 0x28, 0x74, 0x10, 0xc0, 0xfb, 0x76, 0x34, 0x3f, 0x99, 0x2d,
	0xc3, 0x2e, 0x7a, 0xd0, 0xbd, 0xb8, 0x08, 0x7b, 0x93, 0x3f, 0x0e, 0xf8, 0xb3, 0xcd, 0x3b, 0xbd,
	0x01, 0xd7, 0x3a, 0xc6, 0xf6, 0xd8, 0x36, 0x80, 0xf1, 0x70, 0x43, 0xd5, 0xff, 0x41, 0xdc, 0xc1,
	0x03, 0xe8, 0xa5, 0x94, 0xe3, 0x6e, 0xdb, 0xb8, 0x10, 0x32, 0x2f, 0x68, 0x61, 0x2a, 0x21, 0xf3,
	0x87, 0xbd, 0x1f, 0x60, 0xe7, 0x98, 0xcc, 0xd7, 0x6d, 0x2a, 0xff, 0x9e, 0x7a, 0xd4, 0xb2, 0x9f,
	0x94, 0x2a, 0xe2, 0x0e, 0xbe, 0x85, 0xe1, 0x31, 0x99, 0x7a, 0x47, 0x22, 0xaf, 0x15, 0xee, 0xb4,
	0x72, 0x22, 0xcd, 0x74, 0xf2, 0xe0, 0xc6, 0x95, 0x67, 0xd1, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xef, 0x4e, 0xee, 0x91, 0xd9, 0x02, 0x00, 0x00,
}
