// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 登陆方式
type ELoginType int32

const (
	// 账号
	ELoginType_ACCOUNT ELoginType = 0
	// 手机号
	ELoginType_PHONE ELoginType = 1
	// 微信
	ELoginType_WECHAT ELoginType = 2
	// qq
	ELoginType_QQ ELoginType = 3
)

var ELoginType_name = map[int32]string{
	0: "ACCOUNT",
	1: "PHONE",
	2: "WECHAT",
	3: "QQ",
}
var ELoginType_value = map[string]int32{
	"ACCOUNT": 0,
	"PHONE":   1,
	"WECHAT":  2,
	"QQ":      3,
}

func (x ELoginType) String() string {
	return proto.EnumName(ELoginType_name, int32(x))
}
func (ELoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{0}
}

// 登陆方式
type Os int32

const (
	Os_ANDROID Os = 0
	Os_IOS     Os = 1
	Os_WEB     Os = 2
)

var Os_name = map[int32]string{
	0: "ANDROID",
	1: "IOS",
	2: "WEB",
}
var Os_value = map[string]int32{
	"ANDROID": 0,
	"IOS":     1,
	"WEB":     2,
}

func (x Os) String() string {
	return proto.EnumName(Os_name, int32(x))
}
func (Os) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{1}
}

type PUser struct {
	// 用户id
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 登陆账号
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// 手机号
	// 用户名/昵称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 手机号
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// 性别: 0未设置,1男,2女
	Gender int32 `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	// 学校id
	SchoolId int32 `protobuf:"varint,7,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	// 班级id
	ClassId int32 `protobuf:"varint,8,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	// 区域id
	AreaId int32 `protobuf:"varint,9,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	// 认证状态
	IdentityStatus int32 `protobuf:"varint,10,opt,name=identity_status,json=identityStatus,proto3" json:"identity_status,omitempty"`
	// 注册时间
	Created              int32    `protobuf:"varint,11,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUser) Reset()         { *m = PUser{} }
func (m *PUser) String() string { return proto.CompactTextString(m) }
func (*PUser) ProtoMessage()    {}
func (*PUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{0}
}
func (m *PUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUser.Unmarshal(m, b)
}
func (m *PUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUser.Marshal(b, m, deterministic)
}
func (dst *PUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUser.Merge(dst, src)
}
func (m *PUser) XXX_Size() int {
	return xxx_messageInfo_PUser.Size(m)
}
func (m *PUser) XXX_DiscardUnknown() {
	xxx_messageInfo_PUser.DiscardUnknown(m)
}

var xxx_messageInfo_PUser proto.InternalMessageInfo

func (m *PUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PUser) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PUser) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *PUser) GetSchoolId() int32 {
	if m != nil {
		return m.SchoolId
	}
	return 0
}

func (m *PUser) GetClassId() int32 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *PUser) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *PUser) GetIdentityStatus() int32 {
	if m != nil {
		return m.IdentityStatus
	}
	return 0
}

func (m *PUser) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

// 登陆所需结构
type PLoginData struct {
	// 手机号
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	// 验证码
	VerifyCode string `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	// 账号
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// 密码,已使用rsa加密
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// 登陆方式
	LoginType ELoginType `protobuf:"varint,5,opt,name=login_type,json=loginType,proto3,enum=proto.ELoginType" json:"login_type,omitempty"`
	// 登陆设备os
	Os Os `protobuf:"varint,6,opt,name=os,proto3,enum=proto.Os" json:"os,omitempty"`
	// 登陆设备唯一标识
	DeviceId             string   `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PLoginData) Reset()         { *m = PLoginData{} }
func (m *PLoginData) String() string { return proto.CompactTextString(m) }
func (*PLoginData) ProtoMessage()    {}
func (*PLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{1}
}
func (m *PLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLoginData.Unmarshal(m, b)
}
func (m *PLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLoginData.Marshal(b, m, deterministic)
}
func (dst *PLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLoginData.Merge(dst, src)
}
func (m *PLoginData) XXX_Size() int {
	return xxx_messageInfo_PLoginData.Size(m)
}
func (m *PLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_PLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_PLoginData proto.InternalMessageInfo

func (m *PLoginData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PLoginData) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *PLoginData) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PLoginData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PLoginData) GetLoginType() ELoginType {
	if m != nil {
		return m.LoginType
	}
	return ELoginType_ACCOUNT
}

func (m *PLoginData) GetOs() Os {
	if m != nil {
		return m.Os
	}
	return Os_ANDROID
}

func (m *PLoginData) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

// 用户及jwt token信息
// 登陆及注册下使用
type PUserAndToken struct {
	// 用户信息
	User *PUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// jwt token信息
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUserAndToken) Reset()         { *m = PUserAndToken{} }
func (m *PUserAndToken) String() string { return proto.CompactTextString(m) }
func (*PUserAndToken) ProtoMessage()    {}
func (*PUserAndToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{2}
}
func (m *PUserAndToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUserAndToken.Unmarshal(m, b)
}
func (m *PUserAndToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUserAndToken.Marshal(b, m, deterministic)
}
func (dst *PUserAndToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUserAndToken.Merge(dst, src)
}
func (m *PUserAndToken) XXX_Size() int {
	return xxx_messageInfo_PUserAndToken.Size(m)
}
func (m *PUserAndToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PUserAndToken.DiscardUnknown(m)
}

var xxx_messageInfo_PUserAndToken proto.InternalMessageInfo

func (m *PUserAndToken) GetUser() *PUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PUserAndToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 登陆所需结构
type PRegData struct {
	// 手机号
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	// 验证码
	VerifyCode string `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	// 账号
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// 密码,已使用rsa加密
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PRegData) Reset()         { *m = PRegData{} }
func (m *PRegData) String() string { return proto.CompactTextString(m) }
func (*PRegData) ProtoMessage()    {}
func (*PRegData) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{3}
}
func (m *PRegData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PRegData.Unmarshal(m, b)
}
func (m *PRegData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PRegData.Marshal(b, m, deterministic)
}
func (dst *PRegData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PRegData.Merge(dst, src)
}
func (m *PRegData) XXX_Size() int {
	return xxx_messageInfo_PRegData.Size(m)
}
func (m *PRegData) XXX_DiscardUnknown() {
	xxx_messageInfo_PRegData.DiscardUnknown(m)
}

var xxx_messageInfo_PRegData proto.InternalMessageInfo

func (m *PRegData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PRegData) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

func (m *PRegData) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PRegData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 用户已绑定的登录方式信息
type PLoignBindInfo struct {
	// 用户名，没有则为空
	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	// 手机号码，没有则为空
	Phone string `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	// 是否已绑定微信，绑定为true，未绑定为false
	Wechat bool `protobuf:"varint,3,opt,name=Wechat,proto3" json:"Wechat,omitempty"`
	// 是否已绑定QQ，绑定为true，未绑定为false
	QQ bool `protobuf:"varint,7,opt,name=QQ,proto3" json:"QQ,omitempty"`
	// 是否已绑定微博，绑定为true，未绑定为false
	WeiBo                bool     `protobuf:"varint,4,opt,name=WeiBo,proto3" json:"WeiBo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PLoignBindInfo) Reset()         { *m = PLoignBindInfo{} }
func (m *PLoignBindInfo) String() string { return proto.CompactTextString(m) }
func (*PLoignBindInfo) ProtoMessage()    {}
func (*PLoignBindInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{4}
}
func (m *PLoignBindInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLoignBindInfo.Unmarshal(m, b)
}
func (m *PLoignBindInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLoignBindInfo.Marshal(b, m, deterministic)
}
func (dst *PLoignBindInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLoignBindInfo.Merge(dst, src)
}
func (m *PLoignBindInfo) XXX_Size() int {
	return xxx_messageInfo_PLoignBindInfo.Size(m)
}
func (m *PLoignBindInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PLoignBindInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PLoignBindInfo proto.InternalMessageInfo

func (m *PLoignBindInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PLoignBindInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PLoignBindInfo) GetWechat() bool {
	if m != nil {
		return m.Wechat
	}
	return false
}

func (m *PLoignBindInfo) GetQQ() bool {
	if m != nil {
		return m.QQ
	}
	return false
}

func (m *PLoignBindInfo) GetWeiBo() bool {
	if m != nil {
		return m.WeiBo
	}
	return false
}

type PLoignBindInfoList struct {
	List                 []*PLoignBindInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PLoignBindInfoList) Reset()         { *m = PLoignBindInfoList{} }
func (m *PLoignBindInfoList) String() string { return proto.CompactTextString(m) }
func (*PLoignBindInfoList) ProtoMessage()    {}
func (*PLoignBindInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_665cef8693c6b3fa, []int{5}
}
func (m *PLoignBindInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PLoignBindInfoList.Unmarshal(m, b)
}
func (m *PLoignBindInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PLoignBindInfoList.Marshal(b, m, deterministic)
}
func (dst *PLoignBindInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PLoignBindInfoList.Merge(dst, src)
}
func (m *PLoignBindInfoList) XXX_Size() int {
	return xxx_messageInfo_PLoignBindInfoList.Size(m)
}
func (m *PLoignBindInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_PLoignBindInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_PLoignBindInfoList proto.InternalMessageInfo

func (m *PLoignBindInfoList) GetList() []*PLoignBindInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*PUser)(nil), "proto.PUser")
	proto.RegisterType((*PLoginData)(nil), "proto.PLoginData")
	proto.RegisterType((*PUserAndToken)(nil), "proto.PUserAndToken")
	proto.RegisterType((*PRegData)(nil), "proto.PRegData")
	proto.RegisterType((*PLoignBindInfo)(nil), "proto.PLoignBindInfo")
	proto.RegisterType((*PLoignBindInfoList)(nil), "proto.PLoignBindInfoList")
	proto.RegisterEnum("proto.ELoginType", ELoginType_name, ELoginType_value)
	proto.RegisterEnum("proto.Os", Os_name, Os_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountClient interface {
	// 登陆(账号或手机号)
	Login(ctx context.Context, in *PLoginData, opts ...client.CallOption) (*PUserAndToken, error)
	// 注册信息
	Reg(ctx context.Context, in *PString, opts ...client.CallOption) (*PUserAndToken, error)
	// 获取验证码
	GetVerifyCode(ctx context.Context, in *PString, opts ...client.CallOption) (*PBool, error)
	// 获取账号信息(需验证登陆情况)
	GetAccountInfo(ctx context.Context, in *PNoParam, opts ...client.CallOption) (*PUser, error)
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *PInt32, opts ...client.CallOption) (*PUser, error)
}

type accountClient struct {
	c           client.Client
	serviceName string
}

func NewAccountClient(serviceName string, c client.Client) AccountClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto"
	}
	return &accountClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountClient) Login(ctx context.Context, in *PLoginData, opts ...client.CallOption) (*PUserAndToken, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Login", in)
	out := new(PUserAndToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Reg(ctx context.Context, in *PString, opts ...client.CallOption) (*PUserAndToken, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Reg", in)
	out := new(PUserAndToken)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetVerifyCode(ctx context.Context, in *PString, opts ...client.CallOption) (*PBool, error) {
	req := c.c.NewRequest(c.serviceName, "Account.GetVerifyCode", in)
	out := new(PBool)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAccountInfo(ctx context.Context, in *PNoParam, opts ...client.CallOption) (*PUser, error) {
	req := c.c.NewRequest(c.serviceName, "Account.GetAccountInfo", in)
	out := new(PUser)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserInfo(ctx context.Context, in *PInt32, opts ...client.CallOption) (*PUser, error) {
	req := c.c.NewRequest(c.serviceName, "Account.GetUserInfo", in)
	out := new(PUser)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	// 登陆(账号或手机号)
	Login(context.Context, *PLoginData, *PUserAndToken) error
	// 注册信息
	Reg(context.Context, *PString, *PUserAndToken) error
	// 获取验证码
	GetVerifyCode(context.Context, *PString, *PBool) error
	// 获取账号信息(需验证登陆情况)
	GetAccountInfo(context.Context, *PNoParam, *PUser) error
	// 获取用户信息
	GetUserInfo(context.Context, *PInt32, *PUser) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Account{hdlr}, opts...))
}

type Account struct {
	AccountHandler
}

func (h *Account) Login(ctx context.Context, in *PLoginData, out *PUserAndToken) error {
	return h.AccountHandler.Login(ctx, in, out)
}

func (h *Account) Reg(ctx context.Context, in *PString, out *PUserAndToken) error {
	return h.AccountHandler.Reg(ctx, in, out)
}

func (h *Account) GetVerifyCode(ctx context.Context, in *PString, out *PBool) error {
	return h.AccountHandler.GetVerifyCode(ctx, in, out)
}

func (h *Account) GetAccountInfo(ctx context.Context, in *PNoParam, out *PUser) error {
	return h.AccountHandler.GetAccountInfo(ctx, in, out)
}

func (h *Account) GetUserInfo(ctx context.Context, in *PInt32, out *PUser) error {
	return h.AccountHandler.GetUserInfo(ctx, in, out)
}

func init() { proto.RegisterFile("proto/account.proto", fileDescriptor_account_665cef8693c6b3fa) }

var fileDescriptor_account_665cef8693c6b3fa = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x6f, 0xdb, 0x38,
	0x10, 0xb5, 0xe4, 0x2f, 0x79, 0xbc, 0x71, 0x14, 0x6e, 0x76, 0x57, 0xf1, 0x1e, 0x6a, 0xa8, 0x87,
	0xa6, 0x41, 0x9b, 0xb4, 0xce, 0xa5, 0xb7, 0xc2, 0x76, 0x0c, 0x47, 0x40, 0xe0, 0x0f, 0xc5, 0xa9,
	0x8f, 0x06, 0x23, 0x32, 0x8e, 0x50, 0x47, 0x34, 0x44, 0x26, 0x81, 0x2f, 0xfd, 0x27, 0xfd, 0x75,
	0xfd, 0x1f, 0x45, 0xc1, 0xa1, 0x14, 0xc7, 0x01, 0x7a, 0xed, 0x49, 0x7c, 0x33, 0x8f, 0xc3, 0x37,
	0x6f, 0x46, 0xf0, 0xf7, 0x2a, 0x15, 0x4a, 0x9c, 0xd0, 0x28, 0x12, 0xf7, 0x89, 0x3a, 0x46, 0x44,
	0xca, 0xf8, 0x69, 0xba, 0x26, 0x77, 0x4d, 0x25, 0x37, 0x09, 0xff, 0xbb, 0x0d, 0xe5, 0xf1, 0x95,
	0xe4, 0x29, 0x69, 0x80, 0x1d, 0x33, 0xcf, 0x6a, 0x59, 0x87, 0xe5, 0xd0, 0x8e, 0x19, 0xf1, 0xa0,
	0x9a, 0xd5, 0xf0, 0xec, 0x96, 0x75, 0x58, 0x0b, 0x73, 0x48, 0x08, 0x94, 0x12, 0x7a, 0xc7, 0xbd,
	0x22, 0x86, 0xf1, 0x4c, 0xf6, 0xa1, 0xbc, 0xba, 0x15, 0x09, 0xf7, 0x4a, 0x18, 0x34, 0x40, 0x47,
	0xf9, 0x1d, 0x8d, 0x97, 0x5e, 0xd9, 0x44, 0x11, 0x90, 0x7f, 0xa1, 0xb2, 0xe0, 0x09, 0xe3, 0xa9,
	0x57, 0xc1, 0xd7, 0x32, 0x44, 0xfe, 0x87, 0x9a, 0x8c, 0x6e, 0x85, 0x58, 0xce, 0x63, 0xe6, 0x55,
	0x31, 0xe5, 0x98, 0x40, 0xc0, 0xc8, 0x01, 0x38, 0xd1, 0x92, 0x4a, 0xa9, 0x73, 0x0e, 0xe6, 0xaa,
	0x88, 0x03, 0x46, 0xfe, 0x83, 0x2a, 0x4d, 0x39, 0xd5, 0x99, 0x9a, 0x29, 0xa8, 0x61, 0xc0, 0xc8,
	0x1b, 0xd8, 0x8d, 0x19, 0x4f, 0x54, 0xac, 0xd6, 0x73, 0xa9, 0xa8, 0xba, 0x97, 0x1e, 0x20, 0xa1,
	0x91, 0x87, 0x2f, 0x31, 0xaa, 0x7b, 0x8d, 0x52, 0x4e, 0x15, 0x67, 0x5e, 0x3d, 0xab, 0x6d, 0xa0,
	0xff, 0xc3, 0x02, 0x18, 0x5f, 0x88, 0x45, 0x9c, 0x9c, 0x51, 0x45, 0x37, 0x6d, 0x5a, 0xcf, 0xdb,
	0x7c, 0x05, 0xf5, 0x07, 0x9e, 0xc6, 0x37, 0xeb, 0x79, 0x24, 0x18, 0xcf, 0xec, 0x02, 0x13, 0xea,
	0x09, 0xc6, 0x9f, 0x7b, 0x59, 0xdc, 0xf6, 0xb2, 0x09, 0xce, 0x8a, 0x4a, 0xf9, 0x28, 0x52, 0x96,
	0x59, 0xf7, 0x84, 0xc9, 0x07, 0x80, 0xa5, 0x7e, 0x79, 0xae, 0xd6, 0x2b, 0x8e, 0x16, 0x36, 0xda,
	0x7b, 0x66, 0x6e, 0xc7, 0x7d, 0xd4, 0x34, 0x5d, 0xaf, 0x78, 0x58, 0x5b, 0xe6, 0x47, 0x72, 0x00,
	0xb6, 0x90, 0xe8, 0x6a, 0xa3, 0x5d, 0xcb, 0x98, 0x23, 0x19, 0xda, 0x42, 0x6a, 0x73, 0x19, 0x7f,
	0x88, 0x23, 0x9e, 0x9b, 0x5b, 0x0b, 0x1d, 0x13, 0x08, 0x98, 0x3f, 0x80, 0x1d, 0x5c, 0x82, 0x4e,
	0xc2, 0xa6, 0xe2, 0x2b, 0x4f, 0x48, 0x0b, 0x4a, 0xf7, 0x92, 0xa7, 0xd8, 0x66, 0xbd, 0xfd, 0x57,
	0x56, 0x0a, 0x39, 0x21, 0x66, 0xb4, 0x13, 0x4a, 0x53, 0xb3, 0x6e, 0x0d, 0xf0, 0x1f, 0xc1, 0x19,
	0x87, 0x7c, 0xf1, 0xc7, 0xbd, 0xf2, 0xbf, 0x41, 0x63, 0x7c, 0x21, 0xe2, 0x45, 0xd2, 0x8d, 0x13,
	0x16, 0x24, 0x37, 0x42, 0xd7, 0xe9, 0x64, 0x75, 0x8c, 0x80, 0x1c, 0x6a, 0x61, 0x63, 0x14, 0x96,
	0x49, 0x47, 0xa0, 0xb7, 0x72, 0xc6, 0xa3, 0x5b, 0x6a, 0x9e, 0x75, 0xc2, 0x0c, 0xe9, 0xff, 0x62,
	0x32, 0x41, 0xc7, 0x9c, 0xd0, 0x9e, 0x4c, 0xf4, 0xed, 0x19, 0x8f, 0xbb, 0x02, 0x25, 0x38, 0xa1,
	0x01, 0xfe, 0x67, 0x20, 0xdb, 0xef, 0x5f, 0xc4, 0x52, 0x91, 0xb7, 0x50, 0xd2, 0x5f, 0xcf, 0x6a,
	0x15, 0x0f, 0xeb, 0xed, 0x7f, 0x72, 0x1b, 0xb7, 0x88, 0x21, 0x52, 0x8e, 0x3e, 0x01, 0x6c, 0x66,
	0x4a, 0xea, 0x50, 0xed, 0xf4, 0x7a, 0xa3, 0xab, 0xe1, 0xd4, 0x2d, 0x90, 0x1a, 0x94, 0xc7, 0xe7,
	0xa3, 0x61, 0xdf, 0xb5, 0x08, 0x40, 0x65, 0xd6, 0xef, 0x9d, 0x77, 0xa6, 0xae, 0x4d, 0x2a, 0x5a,
	0x98, 0x5b, 0x3c, 0x7a, 0x0d, 0xf6, 0x48, 0xe2, 0x8d, 0xe1, 0x59, 0x38, 0x0a, 0xce, 0xdc, 0x02,
	0xa9, 0x42, 0x31, 0x18, 0x5d, 0xba, 0x96, 0x3e, 0xcc, 0xfa, 0x5d, 0xd7, 0x6e, 0xff, 0xb4, 0x9e,
	0xec, 0x20, 0x6d, 0x28, 0xe3, 0x4b, 0x64, 0x6f, 0x23, 0x28, 0x5b, 0xf0, 0xe6, 0xfe, 0xf3, 0x51,
	0xe7, 0xeb, 0xe0, 0x17, 0xc8, 0x7b, 0x28, 0x86, 0x7c, 0x41, 0x1a, 0x79, 0xfa, 0x52, 0xa5, 0x71,
	0xb2, 0xf8, 0x2d, 0xfd, 0x04, 0x76, 0x06, 0x5c, 0x7d, 0xd9, 0x4c, 0xf5, 0xe5, 0xc5, 0xa7, 0x95,
	0xea, 0x0a, 0xb1, 0xf4, 0x0b, 0xe4, 0x23, 0x34, 0x06, 0x5c, 0x65, 0x0a, 0x71, 0x7e, 0xbb, 0x39,
	0x63, 0x28, 0xc6, 0x34, 0xa5, 0x77, 0xcd, 0xad, 0x2d, 0xf4, 0x0b, 0xe4, 0x1d, 0xd4, 0x07, 0x5c,
	0x69, 0x80, 0xfc, 0x9d, 0x3c, 0x1d, 0x24, 0xea, 0xb4, 0xfd, 0x92, 0x7d, 0x5d, 0x41, 0x78, 0xfa,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x54, 0x6e, 0xd5, 0x1f, 0x05, 0x00, 0x00,
}
