// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/jwt.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EJwtType int32

const (
	EJwtType_PROTO EJwtType = 0
	EJwtType_JSON  EJwtType = 1
)

var EJwtType_name = map[int32]string{
	0: "PROTO",
	1: "JSON",
}
var EJwtType_value = map[string]int32{
	"PROTO": 0,
	"JSON":  1,
}

func (x EJwtType) String() string {
	return proto.EnumName(EJwtType_name, int32(x))
}
func (EJwtType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jwt_686ba6ec2311d898, []int{0}
}

// jwt header信息
type PJwtHeader struct {
	// 默认 "HS256",
	Alg string `protobuf:"bytes,1,opt,name=Alg,proto3" json:"Alg,omitempty"`
	// 默认 JWT
	Typ                  string   `protobuf:"bytes,2,opt,name=Typ,proto3" json:"Typ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PJwtHeader) Reset()         { *m = PJwtHeader{} }
func (m *PJwtHeader) String() string { return proto.CompactTextString(m) }
func (*PJwtHeader) ProtoMessage()    {}
func (*PJwtHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_686ba6ec2311d898, []int{0}
}
func (m *PJwtHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PJwtHeader.Unmarshal(m, b)
}
func (m *PJwtHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PJwtHeader.Marshal(b, m, deterministic)
}
func (dst *PJwtHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PJwtHeader.Merge(dst, src)
}
func (m *PJwtHeader) XXX_Size() int {
	return xxx_messageInfo_PJwtHeader.Size(m)
}
func (m *PJwtHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_PJwtHeader.DiscardUnknown(m)
}

var xxx_messageInfo_PJwtHeader proto.InternalMessageInfo

func (m *PJwtHeader) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

func (m *PJwtHeader) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

// jwt payload信息
type PJwtPayload struct {
	// 用户登录的类型
	LoginType ELoginType `protobuf:"varint,1,opt,name=login_type,json=loginType,proto3,enum=proto.ELoginType" json:"login_type,omitempty"`
	// 用户id
	Uid int32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// token产生时间
	Time int64 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// token对应的客户端类型；ios,android,web
	Os Os `protobuf:"varint,4,opt,name=os,proto3,enum=proto.Os" json:"os,omitempty"`
	// 设备唯一标识
	DeviceId             string   `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PJwtPayload) Reset()         { *m = PJwtPayload{} }
func (m *PJwtPayload) String() string { return proto.CompactTextString(m) }
func (*PJwtPayload) ProtoMessage()    {}
func (*PJwtPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_686ba6ec2311d898, []int{1}
}
func (m *PJwtPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PJwtPayload.Unmarshal(m, b)
}
func (m *PJwtPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PJwtPayload.Marshal(b, m, deterministic)
}
func (dst *PJwtPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PJwtPayload.Merge(dst, src)
}
func (m *PJwtPayload) XXX_Size() int {
	return xxx_messageInfo_PJwtPayload.Size(m)
}
func (m *PJwtPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PJwtPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PJwtPayload proto.InternalMessageInfo

func (m *PJwtPayload) GetLoginType() ELoginType {
	if m != nil {
		return m.LoginType
	}
	return ELoginType_ACCOUNT
}

func (m *PJwtPayload) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PJwtPayload) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PJwtPayload) GetOs() Os {
	if m != nil {
		return m.Os
	}
	return Os_ANDROID
}

func (m *PJwtPayload) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

// jwt token信息
type PJwtToken struct {
	// header
	Header *PJwtHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// playload
	Payload *PJwtPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// sign
	Signature            string   `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PJwtToken) Reset()         { *m = PJwtToken{} }
func (m *PJwtToken) String() string { return proto.CompactTextString(m) }
func (*PJwtToken) ProtoMessage()    {}
func (*PJwtToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_jwt_686ba6ec2311d898, []int{2}
}
func (m *PJwtToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PJwtToken.Unmarshal(m, b)
}
func (m *PJwtToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PJwtToken.Marshal(b, m, deterministic)
}
func (dst *PJwtToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PJwtToken.Merge(dst, src)
}
func (m *PJwtToken) XXX_Size() int {
	return xxx_messageInfo_PJwtToken.Size(m)
}
func (m *PJwtToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PJwtToken.DiscardUnknown(m)
}

var xxx_messageInfo_PJwtToken proto.InternalMessageInfo

func (m *PJwtToken) GetHeader() *PJwtHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PJwtToken) GetPayload() *PJwtPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PJwtToken) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*PJwtHeader)(nil), "proto.PJwtHeader")
	proto.RegisterType((*PJwtPayload)(nil), "proto.PJwtPayload")
	proto.RegisterType((*PJwtToken)(nil), "proto.PJwtToken")
	proto.RegisterEnum("proto.EJwtType", EJwtType_name, EJwtType_value)
}

func init() { proto.RegisterFile("proto/jwt.proto", fileDescriptor_jwt_686ba6ec2311d898) }

var fileDescriptor_jwt_686ba6ec2311d898 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x5f, 0x4f, 0xc2, 0x30,
	0x14, 0xc5, 0x2d, 0x30, 0xa4, 0x97, 0x44, 0xf1, 0xfa, 0x32, 0xff, 0x24, 0x12, 0x9e, 0xd0, 0x18,
	0x24, 0xf8, 0x09, 0x7c, 0x20, 0x51, 0x62, 0x1c, 0x29, 0x7b, 0x27, 0x93, 0x36, 0x58, 0x9d, 0x6b,
	0xc3, 0x3a, 0xc9, 0x5e, 0xfd, 0x1e, 0x7e, 0x57, 0xd3, 0xbb, 0x21, 0x3e, 0xf5, 0xe4, 0xf4, 0xdc,
	0x93, 0xdf, 0x81, 0x63, 0xbb, 0x31, 0xce, 0xdc, 0xbd, 0x6f, 0xdd, 0x88, 0x14, 0x06, 0xf4, 0x9c,
	0x9f, 0x56, 0x7e, 0xb2, 0x5a, 0x99, 0x22, 0xab, 0xff, 0x06, 0x63, 0x80, 0xf9, 0x6c, 0xeb, 0x1e,
	0x55, 0x22, 0xd5, 0x06, 0x7b, 0xd0, 0x7c, 0x48, 0xd7, 0x21, 0xeb, 0xb3, 0x21, 0x17, 0x5e, 0x7a,
	0x27, 0x2e, 0x6d, 0xd8, 0xa8, 0x9c, 0xb8, 0xb4, 0x83, 0x1f, 0x06, 0x5d, 0x7f, 0x32, 0x4f, 0xca,
	0xd4, 0x24, 0x12, 0xc7, 0x00, 0xa9, 0x59, 0xeb, 0x6c, 0xe9, 0x4a, 0xab, 0xe8, 0xf4, 0x68, 0x72,
	0x52, 0xb5, 0x8f, 0xa6, 0xcf, 0xfe, 0x27, 0x2e, 0xad, 0x12, 0x3c, 0xdd, 0x49, 0xdf, 0x59, 0x68,
	0x49, 0x9d, 0x81, 0xf0, 0x12, 0x11, 0x5a, 0x4e, 0x7f, 0xaa, 0xb0, 0xd9, 0x67, 0xc3, 0xa6, 0x20,
	0x8d, 0x67, 0xd0, 0x30, 0x79, 0xd8, 0xa2, 0x3e, 0x5e, 0xf7, 0x45, 0xb9, 0x68, 0x98, 0x1c, 0x2f,
	0x80, 0x4b, 0xf5, 0xa5, 0x57, 0x6a, 0xa9, 0x65, 0x18, 0x10, 0x5a, 0xa7, 0x32, 0x9e, 0xe4, 0xe0,
	0x9b, 0x01, 0xf7, 0x7c, 0xb1, 0xf9, 0x50, 0x19, 0x5e, 0x43, 0xfb, 0x8d, 0xb6, 0x11, 0x59, 0xf7,
	0x8f, 0x6c, 0x3f, 0x5a, 0xd4, 0x01, 0xbc, 0x85, 0x43, 0x5b, 0x6d, 0x22, 0xb4, 0xee, 0x04, 0xff,
	0x65, 0xeb, 0xb5, 0x62, 0x17, 0xc1, 0x4b, 0xe0, 0x0b, 0xbd, 0xce, 0x12, 0x57, 0x6c, 0x14, 0x51,
	0x72, 0xb1, 0x37, 0x6e, 0xae, 0xa0, 0x33, 0xf5, 0x0c, 0x7e, 0x2e, 0x87, 0x60, 0x2e, 0xa2, 0x38,
	0xea, 0x1d, 0x60, 0x07, 0x5a, 0xb3, 0x45, 0xf4, 0xd2, 0x63, 0xaf, 0x6d, 0xaa, 0xbe, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xab, 0x87, 0x3d, 0x9c, 0xad, 0x01, 0x00, 0x00,
}
